import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;

public class CodePreviewWindow extends PApplet {

  String generatedCode = "";
  String statusMessage = "Ready";

  public CodePreviewWindow(String initialCode) {
    this.generatedCode = initialCode;
  }

  public void settings() {
    size(700, 900);
  }

  public void setup() {
    surface.setTitle("StrategyEditor - Code Preview");
    surface.setLocation(1740, 100);
    textFont(createFont("Consolas", 16));
    refreshCode();
  }

  public void draw() {
    background(245);

    fill(230);
    noStroke();
    rect(0, 0, width, 60);

    drawButton(20, 15, 100, 30, "Copy");
    drawButton(140, 15, 100, 30, "Refresh");

    fill(60);
    textAlign(LEFT, CENTER);
    text(statusMessage, 270, 30);

    fill(20);
    textAlign(LEFT, TOP);
    text(generatedCode, 20, 80, width - 40, height - 100);
  }

  void drawButton(float x, float y, float w, float h, String label) {
    fill(210);
    stroke(120);
    rect(x, y, w, h, 6);

    fill(20);
    textAlign(CENTER, CENTER);
    text(label, x + w / 2, y + h / 2);
  }

  public void mousePressed() {
    if (isInside(mouseX, mouseY, 20, 15, 100, 30)) {
      copyToClipboard(generatedCode);
      statusMessage = "Code copied";
      return;
    }

    if (isInside(mouseX, mouseY, 140, 15, 100, 30)) {
      refreshCode();
      statusMessage = "Code refreshed";
      return;
    }
  }

  boolean isInside(float mx, float my, float x, float y, float w, float h) {
    return mx >= x && mx <= x + w && my >= y && my <= y + h;
  }

  void copyToClipboard(String text) {
    StringSelection selection = new StringSelection(text);
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents(selection, null);
  }

  void refreshCode() {
    generatedCode = generateStrategyCode();
  }

  public String generateStrategyCode() {
    String result = "// Strategy generated by StrategyEditor\n";
    result += "// Total points: " + StrategyEditor.points.size() + "\n\n";

    if (StrategyEditor.points.size() == 0) {
      return result;
    }

    StrategyPoint first = StrategyEditor.points.get(0);

    result += "RobotDiff.setPosition("
      + int(first.x_mm) + ", "
      + int(first.y_mm) + ", "
      + round(first.angleDeg) + ", Couleur_Team);\n";

    for (int i = 1; i < StrategyEditor.points.size(); i++) {
      StrategyPoint p = StrategyEditor.points.get(i);

      result += "RobotDiff.Robotgoto("
        + int(p.x_mm) + ", "
        + int(p.y_mm) + ", "
        + round(p.angleDeg) + ", Couleur_Team, NORMALSPEED);";

      if (p.poiName != null) {
        result += "  // Step " + i + " - POI " + p.poiName;
      } else {
        result += "  // Step " + i;
      }

      result += "\n";
    }

    return result;
  }
}
